# Generated by Django 3.1.2 on 2020-11-25 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Culturesubjecttbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('culturesubjectcode', models.CharField(max_length=5)),
                ('subjecttimecode', models.CharField(max_length=20)),
                ('place', models.CharField(max_length=10)),
                ('professorname', models.CharField(max_length=10)),
                ('totalmax', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'culturesubjecttbl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Departmenttbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departmentcode', models.CharField(max_length=3, unique=True)),
                ('departmentname', models.CharField(max_length=20)),
                ('totalnum', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'departmenttbl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fixculturesubjecttbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixculturesubjectcode', models.CharField(max_length=5, unique=True)),
                ('culturesubjectname', models.CharField(max_length=20)),
                ('completescore', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'fixculturesubjecttbl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fixmajorsubjecttbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixmajorsubjectcode', models.CharField(max_length=5, unique=True)),
                ('majorsubjectname', models.CharField(max_length=20)),
                ('completescore', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'fixmajorsubjecttbl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Logintbl',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=15, primary_key=True, serialize=False)),
                ('password', models.CharField(db_column='PASSWORD', max_length=15)),
            ],
            options={
                'db_table': 'logintbl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Majorsubjecttbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('majorsubjectcode', models.CharField(max_length=5)),
                ('subjecttimecode', models.CharField(max_length=20)),
                ('place', models.CharField(max_length=10)),
                ('professorname', models.CharField(max_length=10)),
                ('totalmax', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'majorsubjecttbl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Professorinfotbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_code', models.CharField(max_length=3)),
                ('username', models.CharField(db_column='userName', max_length=10)),
                ('address', models.CharField(max_length=30)),
                ('social_security_num', models.CharField(max_length=15)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_num', models.CharField(max_length=11)),
                ('subject_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'professorinfotbl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Score1Tbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yearsemester', models.CharField(max_length=4)),
                ('subjectcode', models.CharField(max_length=5)),
                ('subjectname', models.CharField(max_length=20)),
                ('rating', models.CharField(max_length=2)),
                ('numrating', models.FloatField()),
            ],
            options={
                'db_table': 'score1tbl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Score2Tbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yearsemester', models.CharField(max_length=4)),
                ('subjectcode', models.CharField(max_length=5)),
                ('subjectname', models.CharField(max_length=20)),
                ('rating', models.CharField(max_length=2)),
                ('numrating', models.FloatField()),
            ],
            options={
                'db_table': 'score2tbl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Studentinfotbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departmentcode', models.CharField(max_length=3)),
                ('username', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=30)),
                ('socialsecuritynum', models.CharField(max_length=15)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('academic', models.CharField(max_length=5)),
                ('phone_num', models.CharField(max_length=11)),
                ('grade', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'studentinfotbl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subjectgroup1Tbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentname', models.CharField(max_length=10)),
                ('assignmentscore', models.SmallIntegerField()),
                ('attendancescore', models.SmallIntegerField()),
                ('midtermexamscore', models.SmallIntegerField()),
                ('finalexamscore', models.SmallIntegerField()),
                ('rating', models.CharField(max_length=2)),
                ('numrating', models.FloatField()),
            ],
            options={
                'db_table': 'subjectgroup1tbl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subjectgroup2Tbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentname', models.CharField(max_length=10)),
                ('assignmentscore', models.SmallIntegerField()),
                ('attendancescore', models.SmallIntegerField()),
                ('midtermexamscore', models.SmallIntegerField()),
                ('finalexam_score', models.SmallIntegerField()),
                ('rating', models.CharField(max_length=2)),
                ('numrating', models.FloatField()),
            ],
            options={
                'db_table': 'subjectgroup2tbl',
                'managed': False,
            },
        ),
    ]
